add method trim line to polygon + tests + document
Flexberry/ember-flexberry-gis pull request #441
Opened 2020-10-19 09:48 UTC by iskakov

Функция trimLineToPolygon находит пересечение линейных объектов и полигона используя библиотеку Jsts.

2020-10-20 04:12 UTC, SnezhanaAbramova commented on addon/mixins/flexberry-map-model-api-expansion.js
> +      let unionres = geojsonWriter.write(resultObject);
почему union?

2020-10-20 04:12 UTC, SnezhanaAbramova commented on addon/mixins/flexberry-map-model-api-expansion.js
> +      const multiObj = {
почему multi?

2020-10-20 04:12 UTC, SnezhanaAbramova commented on addon/mixins/flexberry-map-model-api-expansion.js
> +        reject('objects doesn\' not intersertc');
опечатка

2020-10-20 04:12 UTC, SnezhanaAbramova commented on tests/unit/mixins/flexberry-map-model-api-expansion-trim-line-to-polygon-test.js
> +      [[56.184253, 58.071975],
а сделай координаты целые и прямо нарисуй по клеточкам, тогда результат более очевидный.

2020-10-20 09:30 UTC, SnezhanaAbramova approved these changes

2020-10-27 07:28 UTC, kuzkok requested changes

2020-10-27 07:28 UTC, kuzkok commented on addon/mixins/flexberry-map-model-api-expansion.js
> +      objects.forEach((element, i) => {
цикл тут не надо, только запутывает

2020-10-27 10:55 UTC, kuzkok approved these changes

2020-10-27 10:57 UTC, merged