Wi 204825 register model
Flexberry/ember-flexberry-gis pull request #442
Opened 2020-10-26 04:47 UTC by SnezhanaAbramova

dynamic registration of models

2020-10-30 11:28 UTC, kuzkok commented on addon/components/layers/odata-vector-layer.js
> +    model.reopenClass({
а почему в extend этот namespace сразу не запихать?

2020-10-30 11:28 UTC, kuzkok commented on addon/components/layers/odata-vector-layer.js
> +        resolve();
в резолве хорошо бы что-то передавать, а то получается функция рапортует - "я сделал", а что сделал - приходится искать по сусекам.

2020-10-30 11:28 UTC, kuzkok commented on addon/components/layers/odata-vector-layer.js
> +              let parentMixin = _this.createMixin(dataModel);
а если у parentModel есть свой parent?

2020-10-30 11:28 UTC, kuzkok commented on tests/unit/components/layers/odata-vector-layer-test.js
> +      shape: DS.attr('json'),
а зачем тут запятая?

2020-10-30 11:28 UTC, kuzkok commented on tests/unit/components/layers/odata-vector-layer-test.js
> +  name: 'IISRGISPKDelyankaPolygon32640',
зашивать специфичные для РГИСа наименование в технологию не стоит - надо что-то нейтральное, а имя проекта точно на убрать.

2020-11-06 11:29 UTC, SnezhanaAbramova commented on addon/components/layers/odata-vector-layer.js
> +    model.reopenClass({
через extend, он не запихивается, туда где ожидается

2020-11-09 07:07 UTC, kuzkok requested changes

2020-11-09 07:07 UTC, kuzkok commented on addon/components/layers/odata-vector-layer.js
> +            console.log('Can\'t register model: ' + modelName + ' .Error: ' + e);
не надо в лог писать. или error или ничего, логи только для локального дебага.

2020-11-09 07:07 UTC, kuzkok commented on addon/components/layers/odata-vector-layer.js
> +          url: metadataUrl + modelName + '.json',
этот кусок кода, и в createParent похожие, стоит всё в одну функцию оформить c именем модели и metadataurl, например сreateModelHierarchy() - создаст миксин и модельку, а потом уже туда напихать проекций

2020-11-10 09:54 UTC, kuzkok approved these changes

2020-11-10 09:55 UTC, merged