Fix linter errorrs
Flexberry/ember-flexberry-gis pull request #595
Opened 2022-04-26 06:37 UTC by TeterinaSvetlana

2022-05-12 14:11 UTC, pepelyaeva requested changes

2022-05-12 14:11 UTC, pepelyaeva commented on addon/components/base-vector-layer.js
> -    return new Promise((resolve, reject) => {
Почему удален resolve? он же в этом промисе используется. Здесь а также ниже его везде надо вернуть.

2022-05-12 14:11 UTC, pepelyaeva commented on addon/components/base-vector-layer.js
> +      } catch (error) {
В теле осталось e.error

2022-05-12 14:11 UTC, pepelyaeva commented on addon/components/base-layer.js
> +    defaultLeafletOptionsCallbacks: Object.freeze({
Зачем замораживать, он  же может изменяться? Если для исправления ошибки Only string, number, symbol, ... , то [рекомендовано присваивать значение в init ](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/avoid-leaking-state-in-ember-objects.md)

2022-05-12 14:11 UTC, pepelyaeva commented on addon/components/base-layer.js
> +            l._leafletObject.eachLayer(function () {
Почему удален аргумент? Он же в следующей строчке используется

2022-05-12 14:11 UTC, pepelyaeva commented on addon/components/base-layer.js
> +      return new Promise(() => {
resolve используется ниже, его нужно вернуть

2022-06-07 13:02 UTC, pepelyaeva requested changes

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/base-layer.js
> -    defaultLeafletOptionsCallbacks: {
Надо оставить свойство и задать null

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/base-layer.js
> +        return new Promise((reject) => {
Нужно вернуть resolve

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/base-layer.js
> +        return new Promise((reject) => {
Нужно вернуть resolve

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/flexberry-layers-attributes-panel.js
> +            // }
Нужно убрать комметы

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/flexberry-layers-attributes-panel.js
> +            // }
Нужно убрать комменты

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/flexberry-layers-attributes-panel.js
> -  bufferUnits: {
Вернуть и задать null

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/flexberry-layers-attributes-panel.js
> -  bufferUnits: {
Вернуть и задать null

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/flexberry-layers-attributes-panel.js
> -  _activeTabs: {},
Вернуть и задать null

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/flexberry-layers-attributes-panel.js
> -  _activeTabs: {},
Вернуть и задать null

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/flexberry-layers-attributes-panel.js
> -          _editedRows: {},
Вернуть, null по умолчанию

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/flexberry-layers-attributes-panel.js
> -          _editedRows: {},
Вернуть, null по умолчанию

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/flexberry-layers-attributes-panel.js
> -        const selectedRows = get(tabModel, '_selectedRows');
Почему оно больше не const, оно где-то объявлено?

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/flexberry-layers-attributes-panel.js
> -        const selectedRows = get(tabModel, '_selectedRows');
Почему оно больше не const, оно где-то объявлено?

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/flexberry-layers-intersections-panel.js
> -
Вернуть, задать null

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/flexberry-layers-intersections-panel.js
> -
Вернуть, задать null

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/flexberry-layers-intersections-panel.js
> -
Вернуть

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/flexberry-layers-intersections-panel.js
> -
Вернуть

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/flexberry-layers-intersections-panel.js
> +import Ember from 'ember';
`import { bind } from '@ember/runloop';` и ниже использовать `bind` вместо `Ember.run.bind`

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/flexberry-layers-intersections-panel.js
> +import Ember from 'ember';
import { bind } from '@ember/runloop';

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/flexberry-layers-intersections-panel.js
> +        workingPolygon = polygon;
Это зачем?

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/flexberry-layers-intersections-panel.js
> +        workingPolygon = polygon;
Это зачем?

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/flexberry-map.js
> -
Вернуть

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/flexberry-map.js
> -
Вернуть

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/flexberry-maplayer.js
> -
Вернуть, по умолчанию null

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/flexberry-maplayer.js
> -
Вернуть, по умолчанию null

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/flexberry-maplayer.js
> -    dynamicButtons: [],
Вернуть, по умолчанию null

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/flexberry-maplayer.js
> -    dynamicButtons: [],
Вернуть, по умолчанию null

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/flexberry-maplayer.js
> +
Это откуда?

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/flexberry-maplayer.js
> +
Это откуда?

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/flexberry-maplayers.js
> +
Лишняя  строка

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/flexberry-maplayers.js
> +
Лишняя  строка

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/flexberry-search-panel.js
> +    Ember.keys(localizedProperties).forEach((prop) => {
Object.keys

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/flexberry-search-panel.js
> +    Ember.keys(localizedProperties).forEach((prop) => {
Object.keys

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/flexberry-search.js
> -
Вернуть, задать null

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/flexberry-search.js
> -
Вернуть, задать null

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/flexberry-search.js
> +import Ember from 'ember';
`import $ from 'jquery';` и ниже убрать использовать `$` вместо `Ember.$`

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/flexberry-search.js
> +import Ember from 'ember';
`import $ from 'jquery';` и ниже убрать использовать `$` вместо `Ember.$`

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/geometry-add-modes/draw.js
> -
Вернуть

2022-06-07 13:02 UTC, pepelyaeva commented on addon/components/geometry-add-modes/draw.js
> -
Вернуть, и также ниже везде надо вернуть и задать null

2022-06-09 11:22 UTC, DubrovinPavel commented on addon/components/geometry-add-modes/manual.js
> +              x = p0;
[x,y] = projected

2022-06-09 11:24 UTC, DubrovinPavel commented on addon/components/geometry-add-modes/rhumb.js
> +      const [error] = this.getLayer();
Оба будут 1 элементом массива

2022-06-09 11:31 UTC, DubrovinPavel commented on addon/components/layers-dialogs/add.js
>        },
Тут надо вернуть аргументы, лучше переименовать, чтобы не пересекались с аргументом самой функции request

2022-06-09 11:33 UTC, DubrovinPavel commented on addon/components/layers-dialogs/settings/odata-vector.js
> -  geometryTypes: ['PointPropertyType', 'LineStringPropertyType', 'PolygonPropertyType',
Не надо полностью удалять свойство

2022-06-09 11:49 UTC, DubrovinPavel commented on addon/components/layers/wms-single-tile-layer.js
> +      return innerWmsLayer.identify.apply(this.get('_wmsLayer'), arguments);
innerWmsLayer.identify(...arguments);

2022-06-10 04:18 UTC, DubrovinPavel commented on addon/components/markers-styles/image/icon-editor.js
> +      this.setIsZoom();
Сделать [w, h] = массив

2022-06-10 04:22 UTC, DubrovinPavel commented on addon/helpers/header-from-projection.js
> +      projectionName = arg1;
Снова [modelName, projectionName]

2022-06-10 04:24 UTC, DubrovinPavel commented on addon/initializers/leaflet.js
> +              jsons.push.apply(...feature.features);
.apply в таком случае не нужно

2022-06-10 04:38 UTC, DubrovinPavel commented on addon/layers-styles/-private/categorized.js
> -    @param {Object} options.category Hash containing category settings.
Вернуть, чтобы было описание какие аргументы у этой функции

2022-06-10 04:38 UTC, DubrovinPavel commented on addon/layers-styles/-private/categorized.js
> -    @param {Object} [options.target = 'preview'] Render target ('preview' or 'legend').
Вернуть

2022-06-10 04:45 UTC, DubrovinPavel commented on addon/mixins/flexberry-map-model-api-cosmos.js
> +        condition = filterCondition;
Через [condition]

2022-06-10 04:46 UTC, DubrovinPavel commented on addon/mixins/flexberry-map-model-api-cosmos.js
> +          model = metaModel;
Через [model]

2022-06-10 04:48 UTC, DubrovinPavel commented on addon/mixins/flexberry-map-model-api-savelayer.js
> +      saveFailed = (data) => {
Зачем выносить определение наверх?

2022-06-10 04:50 UTC, DubrovinPavel commented on addon/mixins/flexberry-map-model-api.js
> +              geoJSON = layer;
[geoJSON]

2022-06-10 04:57 UTC, DubrovinPavel commented on addon/mixins/snap-draw.js
> -          const nextIndex = index + 1 === coords.length ? (isPolygon ? 0 : undefined) : index + 1;
Может лучше вернуть и отключить это правило?

2022-06-10 07:31 UTC, TeterinaSvetlana commented on addon/mixins/flexberry-map-model-api-savelayer.js
> +      saveFailed = (data) => {
Его использует метод находящийся выше него

2022-06-16 13:45 UTC, pepelyaeva requested changes

2022-06-16 13:45 UTC, pepelyaeva commented on addon/components/base-layer.js
> +      return new Promise(() => {
Не исправлено

2022-06-16 13:45 UTC, pepelyaeva commented on addon/components/flexberry-edit-layermap.js
> +
А почему здесь обзервер продублирован а не вызван просто, как в других местах?

2022-06-16 13:45 UTC, pepelyaeva commented on addon/components/flexberry-search-panel.js
>  import { computed, get, observer } from '@ember/object';
Тут надо добавить set, удалить импорт Ember во второй строчке, и ниже(в51стр) вместо Ember.set использовать просто set

2022-06-16 13:45 UTC, pepelyaeva commented on addon/components/geometry-add-modes/geoprovider.js
> -  _parsingErrors: {},
Вот тут еще надо вернуть

2022-06-16 13:45 UTC, pepelyaeva commented on addon/components/layers/odata-vector-layer.js
> +      filter = f;
[filter] = equals

2022-06-16 13:45 UTC, pepelyaeva commented on addon/components/flexberry-layers-intersections-panel.js
> +          polygonLayer = layer;
[polygonLayer] = currentFeature.leafletLayer.getLayers()

2022-06-16 13:45 UTC, pepelyaeva commented on addon/components/layers/odata-vector-layer.js
> +          loadedBounds = getLayer;
[loadedBounds] = L.geoJSON(geojsonWriter.write(unionJsts)).getLayers()

2022-06-16 13:45 UTC, pepelyaeva commented on addon/components/layers/wfs-layer.js
> +      filter = f;
[filter] = equals

2022-06-16 13:45 UTC, pepelyaeva commented on addon/components/layers/wfs-layer.js
> +          loadedBounds = getLayer;
[loadedBounds] = L.geoJSON(geojsonWriter.write(unionJsts)).getLayers()

2022-06-16 13:45 UTC, pepelyaeva commented on addon/components/map-commands-dialogs/export.js
> +    '_options.{paperFormat, paperOrientation}',
Надо убрать пробелы. `_options.{paperFormat,paperOrientation}`

2022-06-16 13:45 UTC, pepelyaeva commented on addon/components/map-commands-dialogs/export.js
> +    '_options.{paperFormat, paperOrientation}',
убрать пробелы

2022-06-16 13:45 UTC, pepelyaeva commented on addon/components/map-commands-dialogs/export.js
> +    '_options.{captionLineHeight, captionFontSize}',
убрать пробелы

2022-06-16 13:45 UTC, pepelyaeva commented on addon/components/map-commands-dialogs/export.js
> +    '_options.{captionLineHeight, captionFontFamily, captionFontSize, captionFontColor, captionFontWeight, captionFontStyle, captionFontDecoration}',
убрать пробелы

2022-06-16 13:45 UTC, pepelyaeva commented on addon/components/map-commands-dialogs/export.js
> +    '_options.{captionLineHeight, captionFontFamily, captionFontColor, captionFontWeight, captionFontStyle, captionFontDecoration}',
убрать пробелы

2022-06-16 13:45 UTC, pepelyaeva commented on addon/components/map-commands-dialogs/export.js
> +    '_options.{captionLineHeight, captionFontFamily, captionFontWeight, captionFontStyle, captionFontDecoration, legendControl}',
убрать пробелы

2022-06-16 13:45 UTC, pepelyaeva commented on addon/components/map-commands-dialogs/export.js
> +    'layers.@each.{visibility, isDeleted, legendCanBeDisplayed}',
убрать пробелы

2022-06-16 13:45 UTC, pepelyaeva commented on addon/components/geometry-add-modes/rhumb.js
> +  directionItems: computed('_objectDirections.{[], .@each.active}', 'i18n', function () {
Надо убрать пробел

2022-06-16 13:45 UTC, pepelyaeva commented on addon/components/map-commands-dialogs/export.js
> +    '_options.{displayMode, legendUnderMap}',
и тут

2022-06-16 13:45 UTC, pepelyaeva commented on addon/components/map-commands-dialogs/export.js
> +    '_options.{displayMode, legendUnderMap}',
и тут

2022-06-16 13:45 UTC, pepelyaeva commented on addon/initializers/flexberry-button.js
> +/**
Этот файл зачем?

2022-06-16 13:45 UTC, pepelyaeva commented on addon/layers/wms.js
> +    settings.url = url;
[settings.url] = record.url.split('?')

2022-06-16 13:45 UTC, pepelyaeva commented on addon/map-tools/identify.js
> +      workingPolygon = layerBuff;
[workingPolygon] = buffer.getLayers()

2022-06-16 13:45 UTC, pepelyaeva commented on app/initializers/flexberry-button.js
> +export { default, initialize } from 'ember-flexberry-gis/initializers/flexberry-button';
Это зачем?

2022-06-16 13:45 UTC, pepelyaeva commented on tests/dummy/app/controllers/map.js
> +  sidebarItems: computed('sidebar.{[], @each.active}', 'i18n', function () {
Пробел надо убрать

2022-06-17 07:50 UTC, pepelyaeva approved these changes

2022-06-17 07:56 UTC, merged